export const productSchema = {
  name: "product",
  title: "Productos",
  type: "document",
  fields: [
    {
      name: "name",
      title: "Nombre del Producto",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug (URL amigable)",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "category",
      title: "Categoría",
      type: "string",
      options: {
        list: [
          "Todos",
          "Mixes",
          "Frutos Secos",
          "Fruta Deshidratada",
          "Té e Infusiones",
          "Sin Gluten",
          "Especias",
          "Repostería",
          "Desayuno",
          "Gourmet",
          "Semillas",
          "Cereales y Legumbres",
          "OFERTAS",
        ],
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "price",
      title: "Precio ($)",
      type: "number",
      validation: (Rule: any) => Rule.required().min(0),
    },
    {
      name: "originalPrice",
      title: "Precio Anterior / Tachado ($)",
      type: "number",
    },
    {
      name: "description",
      title: "Descripción",
      type: "text",
      rows: 3,
    },
    {
      name: "image",
      title: "Imagen Principal (Portada)",
      type: "image",
      options: { hotspot: true },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "images",
      title: "Galería de Imágenes Adicionales",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
    },
    {
      name: "weight",
      title: "Peso / Presentación (Ej: 250g, 1L)",
      type: "string",
    },
    {
      name: "tags",
      title: "Etiquetas de Dieta / Filtros",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Vegano", value: "vegano" },
          { title: "Sin TACC / Celíaco", value: "celiaco" },
          { title: "Orgánico", value: "organico" },
          { title: "Natural", value: "natural" },
          { title: "Proteína", value: "proteina" },
          { title: "Artesanal", value: "artesanal" },
          { title: "Popular", value: "popular" },
          { title: "Oferta", value: "oferta" },
        ],
      },
    },
    {
      name: "stock",
      title: "¿Hay Stock Disponible?",
      type: "boolean",
      initialValue: true,
    },
    {
      name: "isNew",
      title: "¿Marcar como Nuevo?",
      type: "boolean",
      initialValue: false,
    },
    {
      name: "isOffer",
      title: "¿Marcar como Oferta?",
      type: "boolean",
      initialValue: false,
    },
  ],
};